# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 823fd765eb94ee390e9c08271b511b6d109250ffeed30c21da2edb18afd0bf65d0e94c3f9d1955c62bc74c1eeb32e15a4ad782062ca8455f8be2f413385a5912

test:
  secret_key_base: 2ec8b8ada1472e185640d6dcdf3fc4168419c4d75f6608628989d5458f595d854a88e29c4444c869ae11f16f3dd84b9a6dd5b76bf52c6cc51d45d9dc94c28f16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
